### ISSUE TITLE
Do you  plan to have new meetup?

### ISSUE THREAD

**Issue by leonids2005** [OrleansContrib/meetups#20]
It so happened I have just watched the last meetup session and it was mentioned that there will be a new one devoted to Kubernetes hosting. It would be great if you actually have it.
There is not a lot of information about the subject, IMO.

Thank you

**Comment by richorama** [comment]
Funnily enough I was chatting with @ReubenBond and @sergeybykov about this earlier this week. I'd be happy to host a meet up. Is anyone prepared to present??

**Comment by leonids2005** [comment]
@ReubenBond and @sergeybykov @richorama IT will be really great if you can do it soon.

**Comment by richorama** [comment]
I have scheduled a meetup about K8s 😎 
https://github.com/OrleansContrib/meetups#meetup-17-simplify-a-k8s-microservices-architecture-with-orleans---vincent-hoogendoorn
