### ISSUE TITLE
Suggestion of WebMeetups service 

### ISSUE THREAD

**Issue by zavg** [OrleansContrib/meetups#3]
Hi guys! Here is a brand new service to do exactly what you are doing using this repo: webmeetups.net. 

You can hold meetups using Google Hangouts on Air, the tool automatically reminds about meetup start in a day and in an hour, deals with time zones, allows you to select active participants and watchers if there are more then 10 attending people. You get rid of Hangouts url and Youtube url copy-pasting, it automatically handles all these things. Also it nicely embeds all YouTube videos in your meetup history.

I am service founder and we just came to production, so I warmly invite you to check out our service. Do not hesitate to ask any questions!

**Comment by richorama** [comment]
Thanks, I'll check it out, as it appears to address quite a few of the problems with Google hangouts 

-----Original Message-----

**Comment by zavg** [comment]
Thanks, your meetup will be warmly welcomed! Do not hesitate to ask for help or to do feature requests.
