### ISSUE TITLE
Guidelines for OrleansContrib

### ISSUE THREAD

**Issue by richorama** [OrleansContrib/meetups#6]
This isn't quite the right place for this discussion, but I'm wondering if some guidelines would be useful for OrleansContrib. I'm not normally a 'rules and regulations' kind of person, but some of the projects have gone a bit stale...

I'd like to maintain a high level of quality, responsiveness to issues / PRs and good documentation.

Therefore I'd like to encourage project owners to try to:
- Respond to issues and pull requests in a timely manner
- Include installation instructions and example usage
- Build and test code with a CI server (preferably [AppVeyor](https://ci.appveyor.com))
- Keep up with Orleans releases

Any thoughts?

**Comment by galvesribeiro** [comment]
:+1: agreed!

**Comment by jkonecki** [comment]
I think it's a good idea.

**Comment by sergeybykov** [comment]
:+1:
