### ISSUE TITLE
Hangout vs. Skype for Business (Lync) for meetups

### ISSUE THREAD

**Issue by sergeybykov** [OrleansContrib/meetups#7]
We tried Lync for https://github.com/OrleansContrib/meetups/#meetup-85-networking-discussion-hosted-by-jason-bragg, and it seems to have worked fine.

Now I'm curious what people think of the Lync vs. Hangout for future meetups.

Seems like the only downside of Lync is the initial install which unfortunately adds the app to autostart.

The upside I see in greater participant capacity, better manageability, and better recording options (with or without chat messages, etc.).

Publishing to youtube, of course, is easier from Hangout.

**Comment by Joshua-Ferguson** [comment]
I am okay with both, but I think Lync edges out ahead.
The text channel for Lync is a definite plus, and we didn't have the problem of it randomly swapping away from the presentation to other people. The initial install might be a barrier.

**Comment by richorama** [comment]
I think lync worked well.

I used the browser plug-in, which still required an install, but is probably easier than installing the full fat client.

Does anyone know the x-plat story for lync?

**Comment by sergeybykov** [comment]
https://play.google.com/store/apps/details?id=com.microsoft.office.lync15
https://itunes.apple.com/us/app/lync-2013-for-iphone/id605841731?mt=8
https://www.microsoft.com/mac/enterprise/lync

**Comment by richorama** [comment]
No Linux then??? ;-)

I ran Ubuntu as my primary OS for a while. Online meetings were the only problem...

**Comment by sergeybykov** [comment]
@richorama There's still hope - http://www.lyncinsider.com/lync-mobile/lync-linux-access-lync-services-linux-computers/. :-)

**Comment by richorama** [comment]
Ha! I'm sold then :-)

**Comment by galvesribeiro** [comment]
Lync/Skype for Business ofc. The quality of the audio/video is much more important than a small problem on client installation. That mistake we can guide users and report this feedback to the product team. 

Also there is a feature that we didn't used which is a whiteboard. We could draw stuff live and make people to colaborate on it.

It would be good if next meetup core team could be on a (big) Surface scree :) skype for business runs perfect there!

So, :+1: to Skype for Business

**Comment by centur** [comment]
As I've installed it already - I'm ok with it now, but It'd be great to provide some form of web-based participation, without any software installations. I remember previously there was a web-client for modern browsers, not sure if it's available for non-office365 users

**Comment by richorama** [comment]
I think we should use hangouts for the next meetup (as planned), and then switch to skype for business thereafter...

**Comment by sergeybykov** [comment]
:+1: We can always switch back later if something becomes a problem.
